In [1]:
import pandas as pd
import numpy as np
from numpy.random import randint

In [2]:
columns= ['W', 'X', 'Y', 'Z'] # four columns
index= ['A', 'B', 'C', 'D', 'E'] # five rows

In [3]:
np.random.seed(42)
data = randint(-100,100,(5,4))

In [4]:
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]])

In [5]:
df = pd.DataFrame(data,index,columns)

In [6]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [7]:
df['W']

A     2
B     6
C     2
D    16
E    30
Name: W, dtype: int64

In [8]:
#List of columns names
df[['W','Z']]

    W   Z
A   2 -86
B   6 -80
C   2 -13
D  16  51
E  30 -99

In [9]:
type(df['W'])

pandas.core.series.Series

In [10]:
#create a new column
df['new'] = df['W'] + df['Y']

In [11]:
df

    W   X   Y   Z  new
A   2  79  -8 -86   -6
B   6 -29  88 -80   94
C   2  21 -26 -13  -24
D  16  -1   3  51   19
E  30  49 -48 -99  -18

In [12]:
# axis=1 due to it being a column
#remove column
df.drop('new',axis=1)

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [13]:
# would need to reassign it
df

    W   X   Y   Z  new
A   2  79  -8 -86   -6
B   6 -29  88 -80   94
C   2  21 -26 -13  -24
D  16  -1   3  51   19
E  30  49 -48 -99  -18

In [14]:
df = df.drop('new',axis=1)

In [15]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [16]:
#select row by name
df.loc['A']

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int64

In [17]:
#select multiple rows
df.loc[['A','C']]

   W   X   Y   Z
A  2  79  -8 -86
C  2  21 -26 -13

In [18]:
#select row by int index
df.iloc[0]

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int64

In [19]:
#select multiple rows by int index
df.iloc[0:2]

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80

In [20]:
#remove row by name
df.drop('C',axis=0)

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
D  16  -1   3  51
E  30  49 -48 -99

In [21]:
#but would need to be reassigned 
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [22]:
#select subsets of rows & columns at the same time
df.loc[['A','C'],['W','Y']]

   W   Y
A  2  -8
C  2 -26

In [23]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [24]:
df>0

      W      X      Y      Z
A  True   True  False  False
B  True  False   True  False
C  True   True  False  False
D  True  False   True   True
E  True   True  False  False

In [25]:
df[df>0]

    W     X     Y     Z
A   2  79.0   NaN   NaN
B   6   NaN  88.0   NaN
C   2  21.0   NaN   NaN
D  16   NaN   3.0  51.0
E  30  49.0   NaN   NaN

In [26]:
df['X']>0

A     True
B    False
C     True
D    False
E     True
Name: X, dtype: bool

In [27]:
df[df['X']>0]

    W   X   Y   Z
A   2  79  -8 -86
C   2  21 -26 -13
E  30  49 -48 -99

In [28]:
df[df['X']>0]['Y']

A    -8
C   -26
E   -48
Name: Y, dtype: int64

In [29]:
df[df['X']>0][['Y','Z']]

    Y   Z
A  -8 -86
C -26 -13
E -48 -99

In [30]:
df[(df['W']>0) & (df['Y'] > 1)]

    W   X   Y   Z
B   6 -29  88 -80
D  16  -1   3  51

In [31]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [32]:
# Reset to default 0,1 to nth index
df.reset_index()

  index   W   X   Y   Z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

In [33]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [34]:
newind = 'CA NY WY OR CO'.split()

In [35]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [36]:
df['Acro'] = newind

In [37]:
df

    W   X   Y   Z Acro
A   2  79  -8 -86   CA
B   6 -29  88 -80   NY
C   2  21 -26 -13   WY
D  16  -1   3  51   OR
E  30  49 -48 -99   CO

In [38]:
df.set_index('Acro')

       W   X   Y   Z
Acro
CA     2  79  -8 -86
NY     6 -29  88 -80
WY     2  21 -26 -13
OR    16  -1   3  51
CO    30  49 -48 -99

In [39]:
df

    W   X   Y   Z Acro
A   2  79  -8 -86   CA
B   6 -29  88 -80   NY
C   2  21 -26 -13   WY
D  16  -1   3  51   OR
E  30  49 -48 -99   CO

In [40]:
df = df.set_index('Acro')

In [41]:
df

       W   X   Y   Z
Acro
CA     2  79  -8 -86
NY     6 -29  88 -80
WY     2  21 -26 -13
OR    16  -1   3  51
CO    30  49 -48 -99

In [42]:
df.describe()

              W          X          Y          Z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

In [43]:
df.dtypes

W    int64
X    int64
Y    int64
Z    int64
dtype: object

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      int64
 1   X       5 non-null      int64
 2   Y       5 non-null      int64
 3   Z       5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes