In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan,4],
                  'B':[5,np.nan,np.nan,8],
                  'C':[10,20,30,40]})

In [3]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [4]:
df.dropna()

     A    B   C
0  1.0  5.0  10
3  4.0  8.0  40

In [5]:
df.dropna(axis=1)

    C
0  10
1  20
2  30
3  40

In [6]:
#threshold
df.dropna(thresh=2)

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
3  4.0  8.0  40

In [7]:
#fill in missing values
df.fillna(value='FILL VALUE')

            A           B   C
0           1           5  10
1           2  FILL VALUE  20
2  FILL VALUE  FILL VALUE  30
3           4           8  40

In [8]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [9]:
df['A'].fillna(value=0)

0    1.0
1    2.0
2    0.0
3    4.0
Name: A, dtype: float64

In [10]:
df['A'].fillna(df['A'].mean())

0    1.000000
1    2.000000
2    2.333333
3    4.000000
Name: A, dtype: float64

In [11]:
df.fillna(df.mean())

          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  20
2  2.333333  6.5  30
3  4.000000  8.0  40